 python tools/create_video.py scene_rt1
 python tools/create_video.py scene_rt2
 python tools/create_video.py scene_rt3
 python tools/create_video.py scene_rt4
 python tools/create_video.py scene_rt5
 python tools/create_video.py scene_rt6
 python tools/create_video.py scene_rt7
 python tools/create_video.py scene_rt8
 python tools/create_video.py scene_rt9
 python tools/create_video.py scene_rt10